### ISSUE TITLE
Issue when doing bol search 

### ISSUE THREAD

**Issue by ascendedcrow** [pennersr/python-bol-api#10]
When trying to execute code
```
    api = OpenAPI(company.boll_api_key)
    response = api.catalog.search("offers=all")
```
I got the error
```
Internal Server Error: /product/sync_products/
Traceback (most recent call last):
  File "C:\Users\ascen\source\repos\BollPriceProcessor\env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ascen\source\repos\BollPriceProcessor\env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ascen\source\repos\BollPriceProcessor\env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ascen\source\repos\BollPriceProcessor\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\ascen\source\repos\BollPriceProcessor\env\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "C:\Users\ascen\source\repos\BollPriceProcessor\product\views.py", line 31, in sync_products
    get_offers(company)
  File "C:\Users\ascen\source\repos\BollPriceProcessor\app\bol_connection\bol_functions.py", line 10, in get_offers
    response = api.catalog.search("offers=all")
  File "C:\Users\ascen\source\repos\BollPriceProcessor\env\lib\site-packages\bol\openapi\api.py", line 37, in search
    return self.request('GET', path, {'q': query})
TypeError: request() takes 3 positional arguments but 4 were given
```

I did fix it with the addition of params to the request method
```
    def request(self, method, path, params={}):
        uri = '/{group}/{version}/{path}'.format(
            group=self.group,
            method=method,
            path=path,
            version=self.api.version)
        return self.api.request(method, uri, params)
```

**Comment by pennersr** [comment]
Closed via 3ebe961
